name: pre-test

# Used by asottile/workflows/.github/workflows/tox.yml when present.
runs:
  using: composite
  steps:
  - name: set USERPROFILE on Windows
    if: runner.os == 'Windows'
    shell: bash
    run: echo 'USERPROFILE=C:\Users\runneradmin' >> "$GITHUB_ENV"  # Standard for GitHub-hosted runners
